#!/bin/bash
# Checks for active clients (IP addresses).
#

. $WAS_BASE_DIR/script_init

[ -n "$EXCLUDED_HOSTS" ] && EXCLUDE="--exclude $EXCLUDED_HOSTS"

ACTIVE_CLIENTS=`nmap -nsP $RANGE $EXCLUDE -oN - | grep "^Host is up" | wc -l`
[ "$DEBUG" == "on" ] && logDebug "Active clients = $ACTIVE_CLIENTS"

EXITSTATUS=$ACTIVE_CLIENTS

exit $EXITSTATUS