#!/bin/bash
# Checks if any active downloads remain in the download directory of rtorrent.
# If no active downloads are found, SIGINT rtorrent

. $WAS_BASE_DIR/script_init

if [ `pidof rtorrent` ]; then
  if [ "$(ls -A $RTORRENT_DOWNLOAD_DIR)" ]; then
    exit 1;
  else
    kill -2 `pidof rtorrent`
  fi
fi

exit 0;
