#!/bin/sh
# Checks if certain processes are still running.

. $WAS_BASE_DIR/script_init

[ -z "$RUNNING_PROCESSES" ] && exit 0;
IFS=","

for process in $RUNNING_PROCESSES
do
  [ `ps -ef | grep $process | grep -vc grep` != 0 ]  && exit 1;
done

exit 0
