#!/bin/bash
# Checks the status of Tvheadend (https://tvheadend.org/projects/tvheadend).
# If no recordings are active or imminent and no users are connected to tvheadend,
# the ACPI wakeup time is set to the next recording
#
# Dependency: curl
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

. $SCRIPT_DIR/../script_init
. $SCRIPT_DIR/../logger-functions

# wakeup script
WAKEUP_SCRIPT="/usr/local/bin/was/wakeup"

rdom () {
  local IFS=\> ; read -d \< E C ;
}

EXITSTATUS=$SHUTDOWN_OK

TVHEADEND_STATUS=$(curl --silent -u "$TV_HEADEND_USERNAME":"$TV_HEADEND_PASSWORD" $TV_HEADEND_STATUS_XML)
while rdom; do
  if [[ $E = start ]]; then
    logInfo "tvheadend: recording active"
    EXITSTATUS=$SHUTDOWN_NOK
    break
  fi
  if [[ $E = next ]]; then
    logInfo "tvheadend: requesting wakeup in $C minutes"
    EXITSTATUS=$($WAKEUP_SCRIPT $C)
    break
  fi
  if [[ $E = subscriptions ]]; then
    if [[ $C -gt 0 ]]; then
      logInfo "tvheadend: $C open subscriptions, no shutdown"
      EXITSTATUS=$SHUTDOWN_NOK
      break
    fi
  fi
done <<< "$TVHEADEND_STATUS"

exit $EXITSTATUS
