#!/bin/bash
# Checks the status of the VDR (Video Disk Recorder).
# If no timers are active or imminent, the ACPI wakeup time is set to the beginning 
# of the next timer

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

. $SCRIPT_DIR/../script_init
. $SCRIPT_DIR/../logger-functions

# wakeup script
WAKEUP_SCRIPT="/usr/local/bin/was/wakeup"

# the relative time in seconds from now of the next timer. 
# The value is zero if no timer is set, negative if a timer
# is running or positiv for a timer in the future
svdrtime=`$SVDRPSEND_CMD NEXT rel | grep -E "^250"`
regex="^250\s*[0-9]*\s*(\-?[0-9]*).*"
if [[ $svdrtime =~ $regex ]]; then
  vdrNextTimer=${BASH_REMATCH[1]}
  # convert seconds to minutes
  vdrNextTimer=$(($vdrNextTimer / 60))
else
  # if no timer is set or another error occured, set default value 0
  vdrNextTimer=0
fi

EXITSTATUS=$($WAKEUP_SCRIPT $vdrNextTimer)

exit $EXITSTATUS
